settings:
  language: en_us # this is the language file used in the lang directory
  protection:
    wild:
      griefing: false #Let players build/break blocks in the wild, building your islands could destroy builds if true.
      creepers: true #false equals no explosions in wild, true they will explode in wild.
                      #includes: creeper, Wither skulls, fireballs, Lighting
    islands:
      notowned:
        griefing: true #Let players build/break blocks on islands with no owners.
        creepers: true #false equals no explosions on islands with no owners, true they will explode on islands with no owners.
                        #includes: creeper, Wither skulls, fireballs, Lighting
      owned:
        creepers: false #false equals no explosions on islands with owner, true they will explode on islands with owner.
                        #includes: creeper, Wither skulls, fireballs, Lighting
  environment:
    distance:
      min: 200 #minimum distance that an island will spawn from the player.
      max: 500 #maximum distance that an island will spawn from the player.
      closest: 500 #This would find the minimum distance to an existing island, pick a random new location, and spawn a new island there.
                   #note: closest has to be equal to or greater that max.
    time: 1800 #how often an island will spawn in seconds
    announce: true #Announce the creation of the island and location to all players.
    count:
      min: 1 #minimum number of islands that will spawn together
      max: 3 #maximum number of islands that will spawn together
  starting: #Setting for player first joining the server
    islands: #Island player will start off with
      - starter
      - oak
      - oak
      - stone
      - stone
      - sand
    random: 1 #number of random island(S) that a player will get in addition to the starting islands.