settings:
  language: en_us # this is the language file used in the lang directory
  protection:
    wild:
      use: true #Lets' players use chest,doors, buttons, ect.
      break: true #Let players break blocks in the wild.
      build: false #Let players build blocks in the wild, building your islands could destroy builds if true.
      ignite: true #Lets' player start fires.
      creepers: true #false equals no explosions in wild, true they will explode in wild.
                      #includes: creeper, Wither skulls, fireballs, Lighting
    islands:
      not_owned:
        use: true #Lets players use chest,doors, buttons, ect
        break: true #Let players break blocks on islands with no owners.
        build: true #Let players build blocks on islands with no owners.
        ignite: false #Lets' player start fires.
        creepers: false #false equals no explosions on islands with no owners, true they will explode on islands with no owners.
                        #includes: creeper, Wither skulls, fireballs, Lighting
      owned:
        creepers: false #false equals no explosions on islands with owner, true they will explode on islands with owner.
                        #includes: creeper, Wither skulls, fireballs, Lighting
  environment:
    default:
      structure: sand #when generating an island and a random one can't be picked which does it replace it with
    distance:
      min: 200 #minimum distance that an island will spawn from the player.
      max: 1000 #the maximum distance that an island will spawn from the player.
      closest: 500 #This would find the minimum distance to an existing island, pick a random new location, and spawn a new island there.
                   #note: closest has to be equal to or greater that max.
    time: 1800 #how often an island will spawn in seconds
    max: 45 #the max number of islands that can spawn around 1 player, -1 do disable this
    major: 4 #the number of islands it takes before an island near spawn is created.
              #this will still work, even if no islands are spawning;
    announce: true #Announce the creation of the island and location to all players.
    count:
      min: 1 #minimum number of structure files that will spawn together to form an island.
      max: 10 #maximum number of structure files that will spawn together to form an island.
  starting: #Setting for player first joining the server
    default:
      shore: sand # The shoreline structure for a new player's island
      inland: grass # The inland structure for any extra space on a new player's island
    size:
      col: 5 #the number of structures in the col multiplied by
      row: 5 #the number of structures in the row, equals the total number a player gets on his island
    structures: #Structure(s) player will start off with, the max amount determined by (col - 2) * (row - 2), example (5-2)*(5-2)=9
      - oak
      - oak
      - starter
      - oak
      - oak
      - stone
      - stone
      - coal