name: ${project.artifactId}
version: '${project.version}'
main: ${project.groupId}.${project.artifactId}
api-version: ${minecraft.api-version}
authors: [ freethemice ]
description: ${project.description}
website: ${project.url}
depend:
  - TitanBoxLibs
commands:
  compass:
    description: island
    usage: /<command>
  com:
    description: island
    usage: /<command>
  cp:
    description: island
    usage: /<command>
  tis:
    description: island
    usage: /<command>
  island:
    description: island
    usage: /<command>
  is:
    description: island
    usage: /<command>
